---
apiVersion: v2
type: application
name: sausage-store
description: Sausage Store Helm Chart

version: 0.1.2
appVersion: "latest"

dependencies:
- name: backend
  repository: file://./charts/backend
  version: 0.1.0
- name: backend-report
  repository: file://./charts/backend-report
  version: 0.1.1
- name: frontend
  repository: file://./charts/frontend
  version: 0.1.0
- name: infra
  repository: file://./charts/infra
  version: 0.1.0